/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.Random;
import javax.swing.JLabel;

/**
 *
 * @author christian
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form tablero
     */
    
    private int[] posicionFicha1 = new int[40];
    private int posicion_ficha1;
    private int esquina = 1;
    private int paso;
    
    private String cadena1 = "";
    private String cadena2 = "";
    private String cadena3 = "";

    private int avanzarCasillas;
    private int valorDado1;
    private int valorDado2;
        
    public Tablero() {
        
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAdorno = new javax.swing.JLabel();
        jLabelFicha1 = new javax.swing.JLabel();
        jLabelFicha2 = new javax.swing.JLabel();
        jLabelFicha3 = new javax.swing.JLabel();
        jLabelFicha4 = new javax.swing.JLabel();
        jLabelTablero = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnJugarDado = new javax.swing.JButton();
        txtDado1 = new javax.swing.JTextField();
        txtDado2 = new javax.swing.JTextField();
        txtAvanzarCasillas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 0, -1, -1));

        jLabelAdorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/login.logo.png"))); // NOI18N
        getContentPane().add(jLabelAdorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 190, -1));

        jLabelFicha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/p_amarillo.png"))); // NOI18N
        jLabelFicha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFicha1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelFicha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, -1, -1));

        jLabelFicha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/p_azul.png"))); // NOI18N
        getContentPane().add(jLabelFicha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        jLabelFicha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/p_naranja.png"))); // NOI18N
        getContentPane().add(jLabelFicha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 660, -1, 30));

        jLabelFicha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/p_verde.png"))); // NOI18N
        getContentPane().add(jLabelFicha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, -1, -1));

        jLabelTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/8463965759_f04799072d_b.jpg"))); // NOI18N
        jLabelTablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTableroMouseClicked(evt);
            }
        });
        jLabelTablero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelTableroKeyPressed(evt);
            }
        });
        getContentPane().add(jLabelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnVolver.setText("Salir");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, -1));

        btnJugarDado.setText("Jugar Dado");
        btnJugarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarDadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugarDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 250, 100, -1));
        getContentPane().add(txtDado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 40, 30));
        getContentPane().add(txtDado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 40, 30));
        getContentPane().add(txtAvanzarCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 40, -1));

        jLabel1.setText("Avanzar Casillas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jLabelTableroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelTableroKeyPressed

    }//GEN-LAST:event_jLabelTableroKeyPressed

    private void jLabelTableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTableroMouseClicked

    }//GEN-LAST:event_jLabelTableroMouseClicked

    private void jLabelFicha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFicha1MouseClicked
        if (esquina == 1){
            jLabelFicha1.setLocation(620-(avanzarCasillas*56),635);
            if (posicion_ficha1 > 10){
                esquina = 2;
                paso = 1;
            }
        }
        
        if (esquina == 2){
            if (paso == 1){
                posicion_ficha1 = posicion_ficha1 - 10;
                jLabelFicha1.setLocation(30,635-(59*posicion_ficha1));
                paso = 2;
            }
            
            if (posicion_ficha1 > 10){
                esquina = 3;
            }else{
                jLabelFicha1.setLocation(30,635-(59*posicion_ficha1));
            }        
            //jLabelFicha1.setLocation(30,635);
        }
        
        if(esquina == 3){
            if (paso == 2){
                posicion_ficha1 = posicion_ficha1 - 10;
                jLabelFicha1.setLocation(50,40);
                paso = 3;
            }
            
            if (posicion_ficha1 > 10){
                esquina = 4;
            }else{
                jLabelFicha1.setLocation(80*posicion_ficha1,40);
            }
        }
        
        if(esquina == 4){
            if(paso == 3){
                posicion_ficha1 = posicion_ficha1 - 10;
                jLabelFicha1.setLocation(40, 40);
                paso = 4;
            }
            
            if(posicion_ficha1 > 10){
                esquina = 5;
            }else{
                jLabelFicha1.setLocation(620, 40*posicion_ficha1);
            }         
        }
    }//GEN-LAST:event_jLabelFicha1MouseClicked

    private void btnJugarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarDadoActionPerformed
        
        Random r1 = new Random();
        Random r2 = new Random();
        
        valorDado1 = r1.nextInt(6)+1;
        valorDado2 = r2.nextInt(6)+1;
        
        avanzarCasillas = valorDado1 + valorDado2;
       
        posicion_ficha1 = posicion_ficha1 + avanzarCasillas;         
        System.out.print(posicion_ficha1);      
        
        cadena1 = String.valueOf(valorDado1);
        cadena2 = String.valueOf(valorDado2);
        cadena3 = String.valueOf(avanzarCasillas);
        
        txtDado1.setText(cadena1);
        txtDado2.setText(cadena2);
        txtAvanzarCasillas.setText(cadena3);
        
    }//GEN-LAST:event_btnJugarDadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugarDado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdorno;
    private javax.swing.JLabel jLabelFicha1;
    private javax.swing.JLabel jLabelFicha2;
    private javax.swing.JLabel jLabelFicha3;
    private javax.swing.JLabel jLabelFicha4;
    private javax.swing.JLabel jLabelTablero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAvanzarCasillas;
    private javax.swing.JTextField txtDado1;
    private javax.swing.JTextField txtDado2;
    // End of variables declaration//GEN-END:variables
}
